config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => "homes#about", as: 'about'

  resources :books, only:[:index, :show, :create, :edit, :update, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resource :book_comments, only:[:create, :destroy]
    end

  resources :users, only:[:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
   favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to:user
  belongs_to:book
  validates :comment, presence: true,length:{maximum:140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def index
    @new_book = Book.new
    @books = Book.all
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@new_book)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
  
  def ensure_correct_user
    @user = Book.find(params[:id]).user
    unless @user == current_user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book_favorite = Favorite.new(user_id: current_user.id, book_id: params[:book_id])
    @book_favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
  @book_favorite = Favorite.find_by(user_id: current_user.id, book_id: params[:book_id])
  @book_favorite.destroy
  redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @new_book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.all
  end

  def index
    @new_book = Book.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
    redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comments.html.erb
<table><% books.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= image_tag book_comment.user.get_profile_image(80,80) %><br>
      <%=link_to user_path(books.user.id) do %><%= book_comment.user.name %><% end %></td>
    <td><%= book_comment.comment %></td>
    <% if book_comment.user == current_user %>
    <td>
      <%= link_to "Destroy", book_book_comments_path(book_comment.book, book_comment), method: :delete,remote: true,class:"btn btn-danger" %>
    </td>
  <% end %>
  </tr>
<% end %>
</table>

<div class="form-group">

  <%= form_with(model:[books, book_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',class:"form-control" %>
  <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/book_comments/_counts.html.erb
コメント数：<%= books.book_comments.count %>

app/views/books/_index.html.erb
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book) do %>
          <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
        <td>
          <%= render 'favorites/favorite', book: book %>
        </td>
        <td>
          <%= render 'book_comments/counts', books: book %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/books/edit.html.erb
<div class="conainer">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>Editing Book</h2>
      <%= render "layouts/errors", new_book: @book %>
      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="book_body">Opinion</label>
        <%= f.text_area :body, class: "form-control" %>
      </div><div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
      <% end %>

      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/errors", new_book: @new_book %>

  <div class="row">
    <%= render "users/info", user: current_user, new_book: @new_book %>
    <%= render "index", books: @books %>
  </div>

</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/errors", new_book: @new_book %>
  <div class="row">

    <%= render "users/info", user: @book.user, new_book: @new_book %>


    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <%= image_tag @user.get_profile_image(80,80) %>
              <br>
              <%= @user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book) do %>
              <%= @book.title %>
            <% end %>
            </td>
          <td><%= @book.body %></td>

          <td>
          <%= render 'favorites/favorite', book: @book %>
          </td>
          <td>
            <%= render 'book_comments/counts', books: @book %>
          </td>

          <% if @user == current_user %>
          <td>
            <%= link_to "Edit", edit_book_path, class: "btn btn-sm btn-success" %>
          </td>
          <td>
            <%= link_to "Destroy", @book, method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %>
          </td>
          <% end %>

        </tr>
      </table>

      <%= render 'book_comments/comments', books: @book, book_comment: @book_comment %>

    </div>


  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book.id), method: :delete do %>
    <span style="color:red;">❤︎</span>
    <%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book.id), method: :book do %>
    <span>❤︎</span>
    <%= book.favorites.count %>
  <% end %>
<% end %>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>
        in
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>
      <p>
        you can share and exchange your opinions ,
        inpressions , and emotions
      </p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block mb-3 sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<div id="error_explanation">
<% if new_book.errors.any? %>
  <h3>
    <%= new_book.errors.count %>errors prohibited this obj from being saved:
  </h3>
  <ul>
    <% new_book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>
          CopyRight Infratop.inc
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
            <i class="fas fa-home"></i>
            Home
          <% end %>
        </li>
        <li>
          <%= link_to users_path, class: 'nav-link text-light' do %>
            <i class="fas fa-users"></i>
            Users
          <% end %>
        </li>
        <li>
          <%= link_to books_path, class: 'nav-link text-light' do %>
            <i class="fas fa-book-open"></i>
            Books
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
            <i class="fas fa-sign-out-alt"></i>
            Log out
          <% end %>
        </li>
        <% else %>
        <li>
          <%= link_to root_path, class: 'nav-link text-light' do %>
            <i class="fas fa-home"></i>
            Home
          <% end %>
        </li>
        <li>
          <%= link_to about_path, class: 'nav-link text-light' do %>
            <i class="fas fa-link"></i>
            About
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
            <i class="fas fa-user-plus"></i>
            Sign up
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
            <i class="fas fa-sign-in-alt"></i>
            Log in
          <% end %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersTwo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
    <%= render 'layouts/header' %>

    <main>
      <%= flash[:notice] %>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/relationships/_follow_list.html.erb
<% if users.exists? %>
  <% users.each do |user| %>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= image_tag user.get_profile_image(80,80) %>
          </td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follow Users</h2>
<%= render 'follow_list', users: @users %>

app/views/relationships/followings.html.erb
<h2>Follower Users</h2>
<%= render 'follow_list', users: @users %>

app/views/users/_index.html.erb
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.get_profile_image(80,80) %>
        </td>
        <td>
          <%= user.name %>
        </td>

        <td>
          <% if user != current_user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>

        <td>
          <%= link_to "Show", user_path(user) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/_info.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag current_user.get_profile_image(100,100) %>
  <table class="table">
    <tboky>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= link_to "#{user.followings.count}", user_followings_path(user) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to "#{user.followers.count}", user_followers_path(user) %></th>
      </tr>
    </tboky>
  </table>
  <div class="row">
    <% if user == current_user %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    <% else %>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
      <% end %>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: new_book do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class: "form-control book_body" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="conainer">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>
      <%= render "layouts/errors", new_book: @user %>
      <%= form_with model: @user do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="user_image">Image</label>
        <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file" %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class: "form-control" %>
      </div><div class="form-group">
        <%= f.submit "Update User", class: "btn btn-success" %>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/errors", new_book: @new_book %>
  <div class="row">

    <%= render "users/info", user: current_user, new_book: @new_book %>
    <%= render "index", users: @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/errors", new_book: @new_book %>
  <div class="row">

    <%= render "info", user: @user, new_book: @new_book %>
    <%= render "books/index", books: @books %>
  </div>
</div>